on: [push]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'allain.com'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run producao
    
      
