name: Instalar o nodeJs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install 
      - run: npm run producao
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'allain.com'
    needs: build
    steps:
      - name: Execute os testes do ambiente de desenvolvimento
        run: npm run producao
    
      
