on: [push]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'allain.com'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Execute os testes do ambiente de desenvolvimento
        run: npm run producao
    
      
